// Search UI copy only. Registry titles, descriptions and categories are
// publisher-authored chain data and are shown verbatim, never translated here.
export const searchCatalog = {
  en: {
    search: 'Search',
    placeholder: 'App, .sea name, height, address or hash',
    resultsFor: 'Results for “{query}”',
    ranking: 'Order: exact name, prefix, then title/description tokens; then distinct on-chain callers over 7 days, then oldest first. No paid placements, publisher boosts, or hidden blocklist.',
    hashPresent: 'Content hash present',
    hashAbsent: 'No content hash',
    hashHelp: 'A content hash identifies published content. It does not endorse the publisher or establish that an app is safe.',
    publisher: 'Publisher',
    url: 'URL',
    category: 'Category',
    registered: 'Registered',
    usage: 'Distinct callers · 7 days',
    usageUnavailable: 'Unavailable',
    lookalike: 'Lookalike / phishing warning: this name resembles “{name}”, which ranks above it. Check the publisher and URL before opening.',
    source: 'Search data read from {url}. The index is built only from chain records.',
    empty: 'No apps or names match this query. Try a .sea name or words from a title or description.',
    prompt: 'Enter an app title, description, or .sea name in the search bar.',
    loading: 'Searching chain records…',
    failed: 'Unable to read search results. Retry or check the node endpoint in Settings.',
    retry: 'Retry search',
    queryTooLong: 'This query exceeds 256 UTF-8 bytes. Use a shorter name or phrase.',
    invalidQuery: 'This search URL has invalid text encoding. Enter the query again in the search bar.',
    notFound: 'No block or transaction matches “{query}”. Try a height, address, hash, app title or .sea name.',
    usageIncomplete: 'The node reached its bounded usage limit. The usage signal is unavailable; results use text match and age.',
    indexIncomplete: 'The node could not index {count} records within its bounds. Search covers a bounded subset of chain records.',
    historyIncomplete: 'This node does not retain the full registry event history. Search covers the chain records available on this node.',
    statusUnavailable: 'This node did not return readable search index status. Index coverage could not be confirmed.',
    sourcesUnconfigured: 'This node has no app or name registry sources configured.',
  },
  ko: {
    search: '검색',
    placeholder: '앱, .sea 이름, 블록 높이, 주소 또는 해시',
    resultsFor: '“{query}” 검색 결과',
    ranking: '순서: 정확한 이름, 접두사, 제목·설명 단어 일치. 이후 최근 7일의 서로 다른 온체인 호출자 수, 오래된 등록순입니다. 유료 배치, 게시자 우대, 숨겨진 차단 목록은 없습니다.',
    hashPresent: '콘텐츠 해시 있음',
    hashAbsent: '콘텐츠 해시 없음',
    hashHelp: '콘텐츠 해시는 게시된 콘텐츠를 식별합니다. 게시자를 보증하거나 앱의 안전성을 확인하는 표시는 아닙니다.',
    publisher: '게시자',
    url: 'URL',
    category: '분류',
    registered: '등록일',
    usage: '서로 다른 호출자 · 7일',
    usageUnavailable: '사용할 수 없음',
    lookalike: '유사 이름 / 피싱 주의: 이 이름은 더 높은 순위의 “{name}”과 비슷합니다. 열기 전에 게시자와 URL을 확인하세요.',
    source: '검색 데이터 출처: {url}. 인덱스는 온체인 기록만으로 구성됩니다.',
    empty: '일치하는 앱이나 이름이 없습니다. .sea 이름이나 제목·설명의 단어로 검색해 보세요.',
    prompt: '검색창에 앱 제목, 설명 또는 .sea 이름을 입력하세요.',
    loading: '온체인 기록 검색 중…',
    failed: '검색 결과를 읽을 수 없습니다. 다시 시도하거나 설정에서 노드 주소를 확인하세요.',
    retry: '다시 검색',
    queryTooLong: '검색어가 UTF-8 기준 256바이트를 초과합니다. 더 짧은 이름이나 문구를 사용하세요.',
    invalidQuery: '검색 URL의 문자 인코딩이 잘못되었습니다. 검색창에 검색어를 다시 입력하세요.',
    notFound: '“{query}”와 일치하는 블록이나 거래가 없습니다. 높이, 주소, 해시, 앱 제목 또는 .sea 이름으로 검색하세요.',
    usageIncomplete: '노드의 사용량 한도에 도달했습니다. 사용량 신호를 사용할 수 없어 텍스트 일치와 등록 시점으로 정렬합니다.',
    indexIncomplete: '노드의 인덱스 한도 내에서 기록 {count}건을 포함할 수 없었습니다. 검색은 온체인 기록의 제한된 일부를 대상으로 합니다.',
    historyIncomplete: '이 노드에는 전체 등록 이벤트 이력이 없습니다. 검색은 이 노드에서 사용할 수 있는 온체인 기록을 대상으로 합니다.',
    statusUnavailable: '노드의 검색 인덱스 상태를 읽을 수 없습니다. 인덱스가 포함하는 기록 범위를 확인할 수 없었습니다.',
    sourcesUnconfigured: '이 노드에는 앱 또는 이름 레지스트리 소스가 설정되어 있지 않습니다.',
  },
  ja: {
    search: '検索',
    placeholder: 'アプリ、.sea名、ブロック高、アドレス、ハッシュ',
    resultsFor: '「{query}」の検索結果',
    ranking: '順序：名前の完全一致、前方一致、タイトル・説明の単語一致。その後、過去7日間の異なるオンチェーン呼び出し元数、登録の古い順です。有料掲載、発行者の優遇、非公開のブロックリストはありません。',
    hashPresent: 'コンテンツハッシュあり',
    hashAbsent: 'コンテンツハッシュなし',
    hashHelp: 'コンテンツハッシュは公開された内容を識別します。発行者の承認やアプリの安全性を示すものではありません。',
    publisher: '発行者',
    url: 'URL',
    category: 'カテゴリ',
    registered: '登録日',
    usage: '異なる呼び出し元 · 7日間',
    usageUnavailable: '利用不可',
    lookalike: '類似名 / フィッシング注意：この名前は上位の「{name}」に似ています。開く前に発行者とURLを確認してください。',
    source: '検索データの取得元：{url}。インデックスはオンチェーン記録のみから構築されます。',
    empty: '一致するアプリや名前はありません。.sea名やタイトル・説明に含まれる単語を試してください。',
    prompt: '検索欄にアプリのタイトル、説明、または.sea名を入力してください。',
    loading: 'オンチェーン記録を検索中…',
    failed: '検索結果を読み取れません。再試行するか、設定でノードの接続先を確認してください。',
    retry: '再検索',
    queryTooLong: '検索語がUTF-8で256バイトを超えています。短い名前や語句を使用してください。',
    invalidQuery: '検索URLの文字エンコーディングが無効です。検索欄にもう一度入力してください。',
    notFound: '「{query}」に一致するブロックや取引はありません。ブロック高、アドレス、ハッシュ、アプリ名、.sea名を試してください。',
    usageIncomplete: 'ノードの使用量上限に達しました。使用量の指標は利用できず、テキスト一致と登録時期で並べます。',
    indexIncomplete: 'ノードのインデックス上限内に{count}件の記録を含められませんでした。検索対象はオンチェーン記録の限られた一部です。',
    historyIncomplete: 'このノードには登録イベントの全履歴がありません。このノードで利用できるオンチェーン記録を検索します。',
    statusUnavailable: 'このノードの検索インデックス状態を読み取れません。対象となる記録の範囲を確認できませんでした。',
    sourcesUnconfigured: 'このノードにはアプリまたは名前レジストリの取得元が設定されていません。',
  },
  'zh-Hans': {
    search: '搜索',
    placeholder: '应用、.sea 名称、区块高度、地址或哈希',
    resultsFor: '“{query}”的搜索结果',
    ranking: '顺序：名称完全匹配、前缀匹配、标题或描述的词语匹配；然后按最近7天不同链上调用者数量、注册时间从早到晚排序。没有付费排名、发布者优待或隐藏屏蔽名单。',
    hashPresent: '有内容哈希',
    hashAbsent: '无内容哈希',
    hashHelp: '内容哈希用于识别已发布的内容，并不代表对发布者的认可或应用安全性认证。',
    publisher: '发布者',
    url: 'URL',
    category: '分类',
    registered: '注册时间',
    usage: '不同调用者 · 7天',
    usageUnavailable: '不可用',
    lookalike: '相似名称 / 钓鱼警告：此名称与排名更高的“{name}”相似。打开前请核对发布者和URL。',
    source: '搜索数据来自 {url}。索引仅由链上记录构建。',
    empty: '没有匹配的应用或名称。请尝试 .sea 名称或标题、描述中的词语。',
    prompt: '请在搜索栏输入应用标题、描述或 .sea 名称。',
    loading: '正在搜索链上记录…',
    failed: '无法读取搜索结果。请重试或在设置中检查节点地址。',
    retry: '重新搜索',
    queryTooLong: '搜索词超过UTF-8编码的256字节。请使用更短的名称或短语。',
    invalidQuery: '搜索URL的文字编码无效。请在搜索栏重新输入。',
    notFound: '没有与“{query}”匹配的区块或交易。请尝试高度、地址、哈希、应用标题或 .sea 名称。',
    usageIncomplete: '节点已达到使用量上限，使用量信号不可用。结果按文本匹配和注册时间排序。',
    indexIncomplete: '节点无法在索引限制内纳入{count}条记录。搜索仅涵盖部分链上记录。',
    historyIncomplete: '此节点未保留完整的注册事件历史。搜索涵盖此节点上可用的链上记录。',
    statusUnavailable: '此节点未返回可读取的搜索索引状态，无法确认索引涵盖的记录范围。',
    sourcesUnconfigured: '此节点未配置应用或名称注册表来源。',
  },
  es: {
    search: 'Buscar',
    placeholder: 'App, nombre .sea, altura, dirección o hash',
    resultsFor: 'Resultados de «{query}»',
    ranking: 'Orden: nombre exacto, prefijo y palabras del título o descripción; después, direcciones distintas que llaman en cadena durante 7 días y registros más antiguos primero. Sin posiciones pagadas, ventajas para editores ni listas de bloqueo ocultas.',
    hashPresent: 'Hash de contenido presente',
    hashAbsent: 'Sin hash de contenido',
    hashHelp: 'Un hash de contenido identifica lo publicado. No avala al editor ni demuestra que una app sea segura.',
    publisher: 'Editor',
    url: 'URL',
    category: 'Categoría',
    registered: 'Fecha de registro',
    usage: 'Direcciones distintas · 7 días',
    usageUnavailable: 'No disponible',
    lookalike: 'Aviso de nombre parecido / phishing: este nombre se parece a «{name}», que aparece antes. Comprueba el editor y la URL antes de abrirlo.',
    source: 'Datos de búsqueda leídos de {url}. El índice se construye solo con registros en cadena.',
    empty: 'No hay apps ni nombres que coincidan. Prueba un nombre .sea o palabras del título o descripción.',
    prompt: 'Introduce el título de una app, su descripción o un nombre .sea en la barra de búsqueda.',
    loading: 'Buscando registros en cadena…',
    failed: 'No se pudieron leer los resultados. Reintenta o comprueba la dirección del nodo en Ajustes.',
    retry: 'Reintentar búsqueda',
    queryTooLong: 'La consulta supera 256 bytes UTF-8. Usa un nombre o frase más corto.',
    invalidQuery: 'La URL de búsqueda tiene una codificación de texto incorrecta. Escribe de nuevo la consulta en la barra.',
    notFound: 'Ningún bloque o transacción coincide con «{query}». Prueba una altura, dirección, hash, título de app o nombre .sea.',
    usageIncomplete: 'El nodo alcanzó su límite de uso. La señal de uso no está disponible; los resultados siguen la coincidencia de texto y la antigüedad.',
    indexIncomplete: 'El nodo no pudo incluir {count} registros dentro de sus límites de índice. La búsqueda cubre una parte limitada de los registros en cadena.',
    historyIncomplete: 'Este nodo no conserva el historial completo de eventos del registro. La búsqueda cubre los registros en cadena disponibles en este nodo.',
    statusUnavailable: 'Este nodo no devolvió un estado legible del índice de búsqueda. No se pudo confirmar qué registros cubre.',
    sourcesUnconfigured: 'Este nodo no tiene configuradas fuentes del registro de apps ni del registro de nombres.',
  },
};

export function resolveSearchLocale(preferences = []) {
  for (const preference of Array.isArray(preferences) ? preferences : [preferences]) {
    const language = String(preference).toLowerCase().split('-')[0];
    if (language === 'zh') return 'zh-Hans';
    if (Object.hasOwn(searchCatalog, language)) return language;
  }
  return 'en';
}

export function searchText(locale, key, values = {}) {
  const template = (searchCatalog[locale] || searchCatalog.en)[key];
  if (template == null) throw new Error(`Unknown search catalog key: ${key}`);
  return template.replace(/\{(\w+)\}/g, (_, name) => String(values[name] ?? ''));
}
