// GENERATED by scripts/gen-design-tokens.py. Do not edit.
import Foundation

enum DesignTokens {
    static let version = "1.1.0"
    struct ColorPair: Equatable, Sendable { let light: UInt32; let dark: UInt32 }
    struct TypeStyle: Equatable, Sendable {
        let size: Double; let line: Double; let tracking: Double
        let family: String; let weight: Int; let iosSize: Double
    }
    struct CubicCurve: Equatable, Sendable { let x1: Double; let y1: Double; let x2: Double; let y2: Double }
    struct SpringSpec: Equatable, Sendable { let response: Double; let dampingFraction: Double; let blendDuration: Double }
    struct ShadowLayer: Equatable, Sendable {
        let hex: UInt32; let opacity: Double; let radius: Double; let x: Double; let y: Double; let spread: Double
    }
    struct ShadowPair: Equatable, Sendable { let light: [ShadowLayer]; let dark: [ShadowLayer] }

    enum Palette {
        static let bg = ColorPair(light: 0xF4EFE6, dark: 0x071320)
        static let surface = ColorPair(light: 0xFBF8F2, dark: 0x0D1C2C)
        static let surfaceSunken = ColorPair(light: 0xECE5D8, dark: 0x0A1826)
        static let line = ColorPair(light: 0xD8CEBB, dark: 0x1F3347)
        static let lineStrong = ColorPair(light: 0xA99F8C, dark: 0x4A6178)
        static let text = ColorPair(light: 0x0D2135, dark: 0xECE6D9)
        static let textMuted = ColorPair(light: 0x4B5B6B, dark: 0x94A4B5)
        static let textInverse = ColorPair(light: 0xF4EFE6, dark: 0x071320)
        static let accent = ColorPair(light: 0x0F5A75, dark: 0x7CC4DC)
        static let accentFill = ColorPair(light: 0x0D2135, dark: 0xE8BF59)
        static let onAccentFill = ColorPair(light: 0xF4EFE6, dark: 0x0D2135)
        static let gold = ColorPair(light: 0xE8BF59, dark: 0xE8BF59)
        static let goldText = ColorPair(light: 0x7E5A0E, dark: 0xE8BF59)
        static let dawn = ColorPair(light: 0xD9673F, dark: 0xF08F6C)
        static let sea = ColorPair(light: 0x0D2135, dark: 0x030B14)
        static let horizon = ColorPair(light: 0xF0DCC0, dark: 0x132A40)
        static let seaLine = ColorPair(light: 0xE8BF59, dark: 0xE8BF59)
        static let success = ColorPair(light: 0x1E7A52, dark: 0x5CCB98)
        static let warn = ColorPair(light: 0xAD6100, dark: 0xFFB857)
        static let danger = ColorPair(light: 0xB42318, dark: 0xFF8A7A)
        static let focus = ColorPair(light: 0x0F5A75, dark: 0x7CC4DC)
        static let textSubtle = ColorPair(light: 0x5F6E7D, dark: 0x7D8EA0)
        static let lineControl = ColorPair(light: 0xC9BFAA, dark: 0x2C4258)
        static let plate = ColorPair(light: 0x0D2135, dark: 0x10263C)
        static let plate2 = ColorPair(light: 0x091A2B, dark: 0x0A1A2B)
        static let plateInk = ColorPair(light: 0xF4EFE6, dark: 0xECE6D9)
        static let plateSoft = ColorPair(light: 0xA9B7C4, dark: 0x94A4B5)
        static let plateSuccess = ColorPair(light: 0x5CCB98, dark: 0x5CCB98)
        static let plateWarn = ColorPair(light: 0xFFB857, dark: 0xFFB857)
    }
    enum TypeScale {
        static let caption = TypeStyle(size: 12, line: 16, tracking: 0.02, family: "text", weight: 400, iosSize: 12)
        static let label = TypeStyle(size: 12, line: 16, tracking: 0.08, family: "mono", weight: 400, iosSize: 12)
        static let footnote = TypeStyle(size: 13, line: 18, tracking: 0, family: "text", weight: 400, iosSize: 13)
        static let body = TypeStyle(size: 16, line: 26, tracking: 0, family: "text", weight: 400, iosSize: 16)
        static let bodyLg = TypeStyle(size: 19, line: 30, tracking: -0.005, family: "text", weight: 400, iosSize: 19)
        static let title3 = TypeStyle(size: 22, line: 28, tracking: -0.01, family: "display", weight: 400, iosSize: 22)
        static let title2 = TypeStyle(size: 30, line: 36, tracking: -0.015, family: "display", weight: 400, iosSize: 30)
        static let title1 = TypeStyle(size: 44, line: 48, tracking: -0.02, family: "display", weight: 400, iosSize: 44)
        static let display = TypeStyle(size: 72, line: 74, tracking: -0.025, family: "display", weight: 400, iosSize: 72)
        static let amountLg = TypeStyle(size: 44, line: 48, tracking: -0.02, family: "amount", weight: 600, iosSize: 44)
        static let bodyUi = TypeStyle(size: 14, line: 20, tracking: 0, family: "text", weight: 400, iosSize: 14)
        static let headline = TypeStyle(size: 15, line: 20, tracking: -0.005, family: "text", weight: 600, iosSize: 15)
        static let amountMd = TypeStyle(size: 40, line: 44, tracking: -0.02, family: "amount", weight: 600, iosSize: 40)
        static let amountXl = TypeStyle(size: 60, line: 64, tracking: -0.02, family: "amount", weight: 600, iosSize: 48)
    }
    enum Space {
        static let s0: Double = 0
        static let s1: Double = 4
        static let s2: Double = 8
        static let s3: Double = 12
        static let s4: Double = 16
        static let s5: Double = 20
        static let s6: Double = 24
        static let s8: Double = 32
        static let s10: Double = 40
        static let s12: Double = 48
        static let s16: Double = 64
        static let s24: Double = 96
        static let s32: Double = 128
    }
    enum Radius {
        static let xs: Double = 4
        static let sm: Double = 8
        static let md: Double = 12
        static let lg: Double = 16
        static let xl: Double = 24
        static let window: Double = 12
        static let pill: Double = 999
        static let plate: Double = 18
    }
    enum Motion {
        static let fast: Double = 0.12
        static let base: Double = 0.24
        static let slow: Double = 0.6
        static let scene: Double = 1.4
        static let standard = CubicCurve(x1: 0.2, y1: 0.7, x2: 0.2, y2: 1)
        static let exit = CubicCurve(x1: 0.4, y1: 0, x2: 1, y2: 1)
        static let panel = SpringSpec(response: 0.32, dampingFraction: 0.86, blendDuration: 0)
        static let sheet = SpringSpec(response: 0.36, dampingFraction: 0.9, blendDuration: 0)
    }
    enum Shadows {
        static let sm = ShadowPair(light: [ShadowLayer(hex: 0x0D2135, opacity: 0.06, radius: 2, x: 0, y: 1, spread: 0), ShadowLayer(hex: 0x0D2135, opacity: 0.05, radius: 8, x: 0, y: 2, spread: 0)], dark: [ShadowLayer(hex: 0x000000, opacity: 0.4, radius: 2, x: 0, y: 1, spread: 0)])
        static let md = ShadowPair(light: [ShadowLayer(hex: 0x0D2135, opacity: 0.06, radius: 4, x: 0, y: 2, spread: 0), ShadowLayer(hex: 0x0D2135, opacity: 0.1, radius: 32, x: 0, y: 12, spread: 0)], dark: [ShadowLayer(hex: 0x000000, opacity: 0.4, radius: 4, x: 0, y: 2, spread: 0), ShadowLayer(hex: 0x000000, opacity: 0.45, radius: 32, x: 0, y: 12, spread: 0)])
        static let window = ShadowPair(light: [ShadowLayer(hex: 0x0D2135, opacity: 0.1, radius: 0, x: 0, y: 0, spread: 1), ShadowLayer(hex: 0x030B14, opacity: 0.45, radius: 80, x: 0, y: 30, spread: -20), ShadowLayer(hex: 0x030B14, opacity: 0.3, radius: 24, x: 0, y: 12, spread: -12)], dark: [ShadowLayer(hex: 0xECE6D9, opacity: 0.1, radius: 0, x: 0, y: 0, spread: 1), ShadowLayer(hex: 0x000000, opacity: 0.8, radius: 80, x: 0, y: 30, spread: -20), ShadowLayer(hex: 0x000000, opacity: 0.6, radius: 24, x: 0, y: 12, spread: -12)])
        static let plate = ShadowPair(light: [ShadowLayer(hex: 0x0D2135, opacity: 0.22, radius: 30, x: 0, y: 14, spread: 0)], dark: [ShadowLayer(hex: 0x000000, opacity: 0.35, radius: 30, x: 0, y: 14, spread: 0)])
    }
}

#if canImport(SwiftUI)
import SwiftUI
#if os(macOS)
import AppKit
#elseif canImport(UIKit)
import UIKit
#endif

extension DesignTokens.ColorPair {
    #if os(macOS)
    func hex(for appearance: NSAppearance) -> UInt32 {
        appearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua ? dark : light
    }
    #endif

    var color: Color {
        #if os(macOS)
        Color(NSColor(name: nil, dynamicProvider: { appearance in
            let hex = self.hex(for: appearance)
            return NSColor(srgbRed: Double((hex >> 16) & 255) / 255, green: Double((hex >> 8) & 255) / 255, blue: Double(hex & 255) / 255, alpha: 1)
        }))
        #elseif canImport(UIKit)
        Color(UIColor { trait in
            let hex = trait.userInterfaceStyle == .dark ? dark : light
            return UIColor(red: Double((hex >> 16) & 255) / 255, green: Double((hex >> 8) & 255) / 255, blue: Double(hex & 255) / 255, alpha: 1)
        })
        #else
        Color(red: Double((light >> 16) & 255) / 255, green: Double((light >> 8) & 255) / 255, blue: Double(light & 255) / 255)
        #endif
    }
}

extension DesignTokens.TypeStyle {
    var font: Font {
        #if os(iOS)
        let pointSize = iosSize
        #else
        let pointSize = size
        #endif
        let fontWeight: Font.Weight = weight >= 600 ? .semibold : (weight >= 500 ? .medium : .regular)
        let design: Font.Design = family == "mono" ? .monospaced : (family.hasPrefix("display") ? .serif : .default)
        let base = Font.system(size: pointSize, weight: fontWeight, design: design)
        return family == "amount" ? base.monospacedDigit() : base
    }
}

extension DesignTokens.CubicCurve {
    func animation(duration: Double) -> Animation { .timingCurve(x1, y1, x2, y2, duration: duration) }
}

extension DesignTokens.SpringSpec {
    var animation: Animation { .spring(response: response, dampingFraction: dampingFraction, blendDuration: blendDuration) }
}

extension DesignTokens.ShadowLayer {
    var color: Color {
        Color(red: Double((hex >> 16) & 255) / 255, green: Double((hex >> 8) & 255) / 255, blue: Double(hex & 255) / 255).opacity(opacity)
    }
}
#endif
