#!/usr/bin/env python3
"""Generate packaged web and Apple tokens. --check never writes files."""
from __future__ import annotations

import argparse
import json
import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEX = re.compile(r"^#[0-9A-Fa-f]{6}$")
NAME = re.compile(r"^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$")
CURVE = re.compile(r"^cubic-bezier\(([^)]+)\)$")
SHADOW = re.compile(
    r"(-?[\d.]+)(?:px)?\s+(-?[\d.]+)(?:px)?\s+(-?[\d.]+)(?:px)?"
    r"(?:\s+(-?[\d.]+)(?:px)?)?\s+rgba\(\s*(\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\s*\)"
)


def number(value, name, minimum=0):
    if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value) or value < minimum:
        raise ValueError(f"{name}: expected finite number >= {minimum}")
    return value


def camel(name):
    parts = name.split("-")
    return parts[0] + "".join(part.capitalize() for part in parts[1:])


def scalar(value):
    return format(value, ".12g")


def px(value):
    return "0" if value == 0 else f"{scalar(value)}px"


def shadow_layers(value):
    layers = []
    matches = list(SHADOW.finditer(value))
    remainder = SHADOW.sub("", value).replace(",", "").strip()
    if not matches or remainder:
        raise ValueError(f"unsupported shadow: {value}")
    for match in matches:
        x, y, blur, spread, r, g, b, opacity = match.groups()
        channels = [int(r), int(g), int(b)]
        if any(channel > 255 for channel in channels) or not 0 <= float(opacity) <= 1 or float(blur) < 0:
            raise ValueError(f"invalid shadow: {value}")
        layers.append((float(x), float(y), float(blur), float(spread or 0), channels, float(opacity)))
    return layers


def validate(t):
    for theme in ("light", "dark"):
        if not t["color"][theme]:
            raise ValueError(f"color.{theme}: empty palette")
        for name, color in t["color"][theme].items():
            if not NAME.fullmatch(name) or not HEX.fullmatch(color["value"]):
                raise ValueError(f"color.{theme}.{name}: expected named #RRGGBB color")
        for value in t["shadow"][theme].values():
            shadow_layers(value)
    for category in ("color", "shadow"):
        if set(t[category]["light"]) != set(t[category]["dark"]):
            raise ValueError(f"{category}: light/dark roles differ")
    for category in ("radius", "motion"):
        entries = t[category] if category == "radius" else t[category]["duration"]
        for name, value in entries.items():
            number(value["value"] if category == "radius" else value, f"{category}.{name}")
    for name, value in t["space"].items():
        if not name.isdigit():
            raise ValueError(f"space.{name}: expected numeric key")
        number(value, f"space.{name}")
    for name, value in t["font"]["scale"].items():
        number(value["size"], f"font.scale.{name}.size", 1)
        number(value["line"], f"font.scale.{name}.line", value["size"])
        number(value["tracking"], f"font.scale.{name}.tracking", -0.04)
        if value["family"] not in t["font"]["family"]:
            raise ValueError(f"font.scale.{name}: unknown family")
        if value.get("weight", "regular") not in t["font"]["weight"]:
            raise ValueError(f"font.scale.{name}: unknown weight")
        if "ios-size" in value:
            number(value["ios-size"], f"font.scale.{name}.ios-size", 1)
    for name, value in t["motion"]["easing"].items():
        match = CURVE.fullmatch(value)
        coords = [] if match is None else [float(n) for n in match[1].split(",")]
        if len(coords) != 4 or not all(math.isfinite(n) for n in coords) or not all(0 <= coords[i] <= 1 for i in (0, 2)):
            raise ValueError(f"motion.easing.{name}: invalid cubic curve")
    for name, spring in t["motion"]["spring"].items():
        number(spring["response"], f"motion.spring.{name}.response", 0.001)
        number(spring["dampingFraction"], f"motion.spring.{name}.dampingFraction", 0.001)
        number(spring["blendDuration"], f"motion.spring.{name}.blendDuration")
        if spring["dampingFraction"] > 1:
            raise ValueError(f"motion.spring.{name}: damping must be <= 1")
    return t


def css(t):
    lines = [f"/* GENERATED by scripts/gen-design-tokens.py; EastSea v{t['version']}. Do not edit. */", "", ":root {", "  color-scheme: light dark;"]
    def emit(name, value):
        lines.append(f"  --{name}: {value};")
    for name, family in t["font"]["family"].items():
        emit(f"font-{name}", family["web"])
    for name, weight in t["font"]["weight"].items():
        emit(f"weight-{name}", weight)
    for name, style in t["font"]["scale"].items():
        for field in ("size", "line"):
            emit(f"text-{name}-{field}", px(style[field]))
        emit(f"text-{name}-tracking", f"{scalar(style['tracking'])}em")
        emit(f"text-{name}-weight", t["font"]["weight"][style.get("weight", "semibold" if style["family"] == "amount" else "regular")])
    for name, value in t["space"].items():
        emit(f"space-{name}", px(value))
    for name, value in t["radius"].items():
        emit(f"radius-{name}", px(value["value"]))
    for name, value in t["motion"]["duration"].items():
        emit(f"dur-{name}", f"{scalar(value)}ms")
    for name, value in t["motion"]["easing"].items():
        emit(f"ease-{name}", value)
    for name, spring in t["motion"]["spring"].items():
        for field, value in spring.items():
            emit(f"spring-{name}-{field}", scalar(value))
    def themed(theme, indent):
        return [f"{indent}--c-{name}: {value['value']};" for name, value in t["color"][theme].items()] + [f"{indent}--shadow-{name}: {value};" for name, value in t["shadow"][theme].items()]
    lines += themed("light", "  ") + ["}", "", ':root[data-theme="light"] { color-scheme: light; }', "", "@media (prefers-color-scheme: dark) {", '  :root:not([data-theme="light"]) {', "    color-scheme: dark;"]
    lines += themed("dark", "    ") + ["  }", "}", "", ':root[data-theme="dark"] {', "  color-scheme: dark;"]
    lines += themed("dark", "  ") + ["}", "", "@media (prefers-reduced-motion: reduce) {", "  :root {"]
    lines += [f"    --dur-{name}: 0ms;" for name in t["motion"]["duration"]] + ["  }", "}", ""]
    return "\n".join(lines)


def swift(t):
    lines = ["// GENERATED by scripts/gen-design-tokens.py. Do not edit.", "import Foundation", "", "enum DesignTokens {", f'    static let version = "{t["version"]}"', "    struct ColorPair: Equatable, Sendable { let light: UInt32; let dark: UInt32 }", "    struct TypeStyle: Equatable, Sendable {", "        let size: Double; let line: Double; let tracking: Double", "        let family: String; let weight: Int; let iosSize: Double", "    }", "    struct CubicCurve: Equatable, Sendable { let x1: Double; let y1: Double; let x2: Double; let y2: Double }", "    struct SpringSpec: Equatable, Sendable { let response: Double; let dampingFraction: Double; let blendDuration: Double }", "    struct ShadowLayer: Equatable, Sendable {", "        let hex: UInt32; let opacity: Double; let radius: Double; let x: Double; let y: Double; let spread: Double", "    }", "    struct ShadowPair: Equatable, Sendable { let light: [ShadowLayer]; let dark: [ShadowLayer] }", "", "    enum Palette {"]
    for name, light in t["color"]["light"].items():
        dark = t["color"]["dark"][name]["value"]
        lines.append(f"        static let {camel(name)} = ColorPair(light: 0x{light['value'][1:]}, dark: 0x{dark[1:]})")
    lines += ["    }", "    enum TypeScale {"]
    for name, style in t["font"]["scale"].items():
        weight = t["font"]["weight"][style.get("weight", "semibold" if style["family"] == "amount" else "regular")]
        lines.append(f'        static let {camel(name)} = TypeStyle(size: {scalar(style["size"])}, line: {scalar(style["line"])}, tracking: {scalar(style["tracking"])}, family: "{style["family"]}", weight: {weight}, iosSize: {scalar(style.get("ios-size", style["size"]))})')
    lines += ["    }", "    enum Space {"] + [f"        static let s{name}: Double = {scalar(value)}" for name, value in t["space"].items()] + ["    }", "    enum Radius {"]
    lines += [f"        static let {camel(name)}: Double = {scalar(value['value'])}" for name, value in t["radius"].items()] + ["    }", "    enum Motion {"]
    lines += [f"        static let {camel(name)}: Double = {scalar(value / 1000)}" for name, value in t["motion"]["duration"].items()]
    for name, value in t["motion"]["easing"].items():
        coords = [float(n) for n in CURVE.fullmatch(value)[1].split(",")]
        lines.append(f"        static let {camel(name)} = CubicCurve(" + ", ".join(f"{k}: {scalar(v)}" for k, v in zip(("x1", "y1", "x2", "y2"), coords)) + ")")
    for name, spring in t["motion"]["spring"].items():
        lines.append(f"        static let {camel(name)} = SpringSpec(" + ", ".join(f"{k}: {scalar(v)}" for k, v in spring.items()) + ")")
    lines += ["    }", "    enum Shadows {"]
    for name in t["shadow"]["light"]:
        arrays = []
        for theme in ("light", "dark"):
            layers = []
            for x, y, radius, spread, channels, opacity in shadow_layers(t["shadow"][theme][name]):
                hex_value = "".join(f"{c:02X}" for c in channels)
                layers.append(f"ShadowLayer(hex: 0x{hex_value}, opacity: {scalar(opacity)}, radius: {scalar(radius)}, x: {scalar(x)}, y: {scalar(y)}, spread: {scalar(spread)})")
            arrays.append(f"{theme}: [" + ", ".join(layers) + "]")
        lines.append(f"        static let {camel(name)} = ShadowPair(" + ", ".join(arrays) + ")")
    lines += ["    }", "}", "", SWIFT_ADAPTER, ""]
    return "\n".join(lines)


SWIFT_ADAPTER = '''#if canImport(SwiftUI)
import SwiftUI
#if os(macOS)
import AppKit
#elseif canImport(UIKit)
import UIKit
#endif

extension DesignTokens.ColorPair {
    #if os(macOS)
    func hex(for appearance: NSAppearance) -> UInt32 {
        appearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua ? dark : light
    }
    #endif

    var color: Color {
        #if os(macOS)
        Color(NSColor(name: nil, dynamicProvider: { appearance in
            let hex = self.hex(for: appearance)
            return NSColor(srgbRed: Double((hex >> 16) & 255) / 255, green: Double((hex >> 8) & 255) / 255, blue: Double(hex & 255) / 255, alpha: 1)
        }))
        #elseif canImport(UIKit)
        Color(UIColor { trait in
            let hex = trait.userInterfaceStyle == .dark ? dark : light
            return UIColor(red: Double((hex >> 16) & 255) / 255, green: Double((hex >> 8) & 255) / 255, blue: Double(hex & 255) / 255, alpha: 1)
        })
        #else
        Color(red: Double((light >> 16) & 255) / 255, green: Double((light >> 8) & 255) / 255, blue: Double(light & 255) / 255)
        #endif
    }
}

extension DesignTokens.TypeStyle {
    var font: Font {
        #if os(iOS)
        let pointSize = iosSize
        #else
        let pointSize = size
        #endif
        let fontWeight: Font.Weight = weight >= 600 ? .semibold : (weight >= 500 ? .medium : .regular)
        let design: Font.Design = family == "mono" ? .monospaced : (family.hasPrefix("display") ? .serif : .default)
        let base = Font.system(size: pointSize, weight: fontWeight, design: design)
        return family == "amount" ? base.monospacedDigit() : base
    }
}

extension DesignTokens.CubicCurve {
    func animation(duration: Double) -> Animation { .timingCurve(x1, y1, x2, y2, duration: duration) }
}

extension DesignTokens.SpringSpec {
    var animation: Animation { .spring(response: response, dampingFraction: dampingFraction, blendDuration: blendDuration) }
}

extension DesignTokens.ShadowLayer {
    var color: Color {
        Color(red: Double((hex >> 16) & 255) / 255, green: Double((hex >> 8) & 255) / 255, blue: Double(hex & 255) / 255).opacity(opacity)
    }
}
#endif'''


def outputs(root, t, components):
    generated = css(t)
    files = {root / "apps/wallet/Sources/DesignTokens.swift": swift(t)}
    for folder, name in (("site", "tokens.css"), ("apps/extension/ui", "design-tokens.css"), ("apps/explorer", "design-tokens.css"), ("design/generated/toolbox", "design-tokens.css")):
        files[root / folder / name] = generated
        files[root / folder / "design-components.css"] = "/* GENERATED copy of design/brand/components.css. Do not edit. */\n" + components
    return files


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if any packaged token or component file is stale")
    args = parser.parse_args(argv)
    try:
        tokens = validate(json.loads((ROOT / "design/brand/tokens.json").read_text()))
        files = outputs(ROOT, tokens, (ROOT / "design/brand/components.css").read_text())
    except (ValueError, KeyError, OSError, TypeError) as error:
        print(f"design tokens: {error}", file=sys.stderr)
        return 2
    stale = [path for path, content in files.items() if not path.exists() or path.read_text() != content]
    if args.check:
        if stale:
            for path in stale:
                print(f"DRIFT {path.relative_to(ROOT)}", file=sys.stderr)
            print("Run python3 scripts/gen-design-tokens.py", file=sys.stderr)
            return 1
        print(f"design tokens: {len(files)} generated files match v{tokens['version']}")
        return 0
    for path in stale:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(files[path])
        print(f"generated {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
