#!/usr/bin/env python3
"""Generate the pinned, dependency-free UTS-39 tables from Unicode 16 data.

Inputs: confusables-16.txt and UnicodeData-16.txt in the supplied directory.
Download official source files into the workspace's tmp/ directory first.
"""
import argparse
import hashlib
from pathlib import Path


def rust_string(points):
    return '"' + ''.join(f"\\u{{{point:x}}}" for point in points) + '"'


def generate(inputs, output):
    confusables = inputs / "confusables-16.txt"
    unicode_data = inputs / "UnicodeData-16.txt"
    mappings = {}
    for line in confusables.read_text().splitlines():
        row = line.split("#", 1)[0].strip()
        if row:
            source, target, _ = (part.strip() for part in row.split(";"))
            points = [int(point, 16) for point in source.split()]
            assert len(points) == 1
            mappings[points[0]] = [int(point, 16) for point in target.split()]
    decompositions, classes = {}, {}
    for line in unicode_data.read_text().splitlines():
        fields = line.split(";")
        point = int(fields[0], 16)
        if int(fields[3]):
            classes[point] = int(fields[3])
        if fields[5] and not fields[5].startswith("<"):
            decompositions[point] = [int(part, 16) for part in fields[5].split()]
    lines = [
        "// Generated by scripts/generate-search-unicode.py; do not edit.",
        "// Unicode 16.0.0, Unicode License V3 (search-unicode/LICENSE).",
        "// https://www.unicode.org/Public/security/16.0.0/confusables.txt",
        "// https://www.unicode.org/Public/16.0.0/ucd/UnicodeData.txt",
    ]
    for path in (confusables, unicode_data):
        lines.append(f"// {path.name} sha256: {hashlib.sha256(path.read_bytes()).hexdigest()}")
    for name, rows in (("CONFUSABLES", mappings), ("DECOMPOSITIONS", decompositions)):
        lines.append(f"pub const {name}: &[(u32, &str)] = &[")
        lines.extend(f"    (0x{point:x}, {rust_string(target)})," for point, target in sorted(rows.items()))
        lines.append("];")
    lines.append("pub const COMBINING_CLASSES: &[(u32, u8)] = &[")
    lines.extend(f"    (0x{point:x}, {value})," for point, value in sorted(classes.items()))
    lines.append("];")
    output.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("inputs", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    generate(args.inputs, args.output)
