#!/usr/bin/env node
// Generates site/tokens.css from design/brand/tokens.json (the single source of
// truth for the EastSea design system). Run from the repo root:
//   node design/scripts/build-tokens.mjs          # write site/tokens.css
//   node design/scripts/build-tokens.mjs --check  # exit 1 if tokens.css is stale
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const SRC = join(root, "design/brand/tokens.json");
const OUT = join(root, "site/tokens.css");

const HEX = /^#[0-9A-Fa-f]{6}$/;

function load() {
  const t = JSON.parse(readFileSync(SRC, "utf8"));
  for (const mode of ["light", "dark"]) {
    const roles = t.color?.[mode];
    if (!roles) throw new Error(`tokens.json: color.${mode} missing`);
    for (const [k, v] of Object.entries(roles)) {
      if (!HEX.test(v.value)) throw new Error(`tokens.json: color.${mode}.${k} is not #RRGGBB`);
    }
  }
  const lightKeys = Object.keys(t.color.light).sort().join();
  const darkKeys = Object.keys(t.color.dark).sort().join();
  if (lightKeys !== darkKeys) throw new Error("tokens.json: light and dark colour roles differ");
  return t;
}

const px = (n) => (n === 0 ? "0" : `${n}px`);

function colorVars(roles, indent) {
  return Object.entries(roles).map(([k, v]) => `${indent}--c-${k}: ${v.value};`);
}

function shadowVars(shadows, indent) {
  return Object.entries(shadows).map(([k, v]) => `${indent}--shadow-${k}: ${v};`);
}

function staticVars(t) {
  const out = [];
  for (const [k, v] of Object.entries(t.font.family)) out.push(`  --font-${k}: ${v.web};`);
  for (const [k, v] of Object.entries(t.font.weight)) out.push(`  --weight-${k}: ${v};`);
  for (const [k, v] of Object.entries(t.font.scale)) {
    out.push(`  --text-${k}-size: ${px(v.size)};`);
    out.push(`  --text-${k}-line: ${px(v.line)};`);
    out.push(`  --text-${k}-tracking: ${v.tracking}em;`);
  }
  for (const [k, v] of Object.entries(t.space)) out.push(`  --space-${k}: ${px(v)};`);
  for (const [k, v] of Object.entries(t.radius)) out.push(`  --radius-${k}: ${px(v.value)};`);
  for (const [k, v] of Object.entries(t.motion.duration)) out.push(`  --dur-${k}: ${v}ms;`);
  for (const [k, v] of Object.entries(t.motion.easing)) out.push(`  --ease-${k}: ${v};`);
  return out;
}

function render(t) {
  const dark = [...colorVars(t.color.dark, "    "), ...shadowVars(t.shadow.dark, "    ")];
  return [
    `/* GENERATED by design/scripts/build-tokens.mjs from design/brand/tokens.json`,
    `   (EastSea design system v${t.version}). Do not edit by hand. */`,
    ``,
    `:root {`,
    `  color-scheme: light dark;`,
    ...staticVars(t),
    ...colorVars(t.color.light, "  "),
    ...shadowVars(t.shadow.light, "  "),
    `}`,
    ``,
    `@media (prefers-color-scheme: dark) {`,
    `  :root:not([data-theme="light"]) {`,
    ...dark,
    `  }`,
    `}`,
    ``,
    `:root[data-theme="dark"] {`,
    ...dark.map((l) => l.slice(2)),
    `}`,
    ``,
  ].join("\n");
}

const css = render(load());
if (process.argv.includes("--check")) {
  const cur = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (cur !== css) {
    console.error("site/tokens.css is stale: run node design/scripts/build-tokens.mjs");
    process.exit(1);
  }
  console.log("site/tokens.css is up to date");
} else {
  writeFileSync(OUT, css);
  console.log(`wrote ${OUT}`);
}
