#!/usr/bin/env node
// Compatibility entrypoint; every platform is generated by the one Python script.
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
const script = fileURLToPath(new URL("../../scripts/gen-design-tokens.py", import.meta.url));
const result = spawnSync("python3", [script, ...process.argv.slice(2)], { stdio: "inherit" });
if (result.error) console.error(result.error.message);
process.exit(result.status ?? 2);
